name: My First Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello, CI/CD is working!"
